<a href="https://colab.research.google.com/github/DCI-alxogm/ml2023-alxogm/blob/main/Ago11-12/miprimerNB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

$y=y^2$

In [29]:
lista1=[2,"2","dos",2.0]

In [15]:
lista1

[2, '2', 'dos', 2.0]

In [16]:
lista2=["4","cuatro"]

In [17]:
lista1+lista2

[2, '2', 'dos', 2.0, '4', 'cuatro']

In [18]:
lista1*lista2

TypeError: ignored

In [20]:
lista1*3.3


TypeError: ignored

In [21]:
lista1.append(4)

In [22]:
lista1

[2, '2', 'dos', 2.0, 4]

In [27]:
lista1.remove

In [30]:
del lista1[2]

In [31]:
lista1

[2, '2', 2.0]

In [33]:
lista1.insert(2,'tres')

In [34]:
lista1

[2, '2', 'tres', 2.0]

In [38]:
?lista1.insert

In [41]:
lista1.insert?

In [39]:
lista3=[lista1,lista2]

In [40]:
lista3

[[2, '2', 'tres', 2.0], ['4', 'cuatro']]

In [42]:
for i in lista1:
  print(i)

2
2
tres
2.0


In [44]:
for i in range(0,len(lista1)):
  print(i,lista1[i])

0 2
1 2
2 tres
3 2.0


In [45]:
for i,item in enumerate(lista1):
  print(i,item)

0 2
1 2
2 tres
3 2.0


In [46]:
enumerate?

In [47]:
lista1=(2,"2","dos",2.0)

In [49]:
type(lista1)

tuple

In [50]:
import array as arr

In [62]:
arreglo=arr.array("i",[1,2,3])

In [63]:
arreglo

array('i', [1, 2, 3])

In [64]:
arreglo2=arr.array("i",[2,3,4])

In [66]:
arreglo2

array('i', [2, 3, 4, 2, 3, 4])

In [67]:
import numpy as np

In [69]:
nparr1=np.array([1,2,3])
nparr2=np.array([4,5,6])

In [70]:
nparr1*2

array([2, 4, 6])

In [71]:
nparr1*nparr2

array([ 4, 10, 18])

In [72]:
np.dot(nparr1,nparr2)

32

In [73]:
nparr1/nparr2

array([0.25, 0.4 , 0.5 ])